version: '2'

services:
  web:
    build: .
    command: npm run serve
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      - .:/nodeyard
    links:
      - postgres
      - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: nodeyard
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379'
